export { SearchPage } from './SearchPage/SearchPage'
export { SearchFormPage } from './SearchFormPage/SearchFormPage'
export { ResultsPanelPage } from './ResultsPanelPage/ResultsPanelPage'
export { ResultsListPage } from './ResultsListPage/ResultsListPage'
export { PersonDetailPage } from './PersonDetailPage/PersonDetailPage'
export { MovieDetailPage } from './MovieDetailPage/MovieDetailPage'
